CONNECT / AS SYSDBA;
ALTER SESSION SET CONTAINER = XEPDB1;

DROP USER localadmin CASCADE;
CREATE USER localadmin IDENTIFIED BY "LocalAdmin123";
GRANT CONNECT, RESOURCE TO localadmin;
GRANT CREATE SESSION TO localadmin;
ALTER USER localadmin QUOTA UNLIMITED ON USERS;

SELECT * FROM dba_sys_privs WHERE grantee = 'localadmin';
