version: '3.9'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    container_name: api-sermed
    restart: always
    tty: true
    volumes:
      - .:/home/node/app/
    networks:
      - sermed-networks

networks:
  sermed-networks:
    driver: bridge
