version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: database-sermed
    environment:
      - ORACLE_PWD=Oracle_123
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - ./database:/opt/oracle/oradata
      - ./scripts/init_script.sh:/opt/oracle/scripts/startup/init_script.sh
      - ./scripts/sql/create_user.sql:/opt/oracle/scripts/startup/create_user.sql
    networks:
      - sermed-networks
    healthcheck:
      test: ['CMD', 'sqlplus', '-S', '/ as sysdba', 'EXIT']
      interval: 30s
      timeout: 10s
      retries: 10

  app:
    build: .
    ports:
      - '3333:3333'
    container_name: api-sermed
    restart: always
    tty: true
    volumes:
      - .:/home/node/app/
    networks:
      - sermed-networks
    depends_on:
      oracle-db:
        condition: service_healthy
    command: ['/bin/bash', './scripts/wait-for-oracle.sh']

networks:
  sermed-networks:
    driver: bridge
