version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3333:3333
    container_name: api-sermed
    restart: always
    tty: true
    volumes:
      - .:/home/node/app/
    networks:
      - sermed-networks

networks:
  sermed-networks:
    driver: bridge
